apiVersion: v1
kind: Service
metadata:
  name: rails-service
spec:
  selector:
    app: rails
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080  # Explicit NodePort specify
  type: NodePort
